# 相当于脚本用途的一个声明
name: deploy

# 触发脚本的事件
on:
  # 支持手动触发构建
  workflow_dispatch:
  release:
    # 创建release的时候触发
    types: [published]

# 定义一个发行任务
jobs:
  deploy:
    # 任务运行的环境
    runs-on: ubuntu-latest
    # 任务的步骤
    steps:
      # 1. 声明 checkout 仓库代码到工作区
      - uses: actions/checkout@v2
      # 2. 安装Java 环境 这里会用到的参数就是 Git Action secrets中配置的，
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # 3. 设置Maven中央仓库配置
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: releases
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-passphrase:  MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      # 4. 发布到Maven中央仓库
      - name: Publish to Apache Maven Central
        # 执行maven deploy命令
        run: mvn clean deploy -P release -Dcheckstyle.skip
        env:
          # Nexus用户名
          MAVEN_USERNAME: MAVEN_CENTRAL_USERNAME
          # Nexus密码
          MAVEN_CENTRAL_TOKEN: MAVEN_CENTRAL_TOKEN
          # gpg短密码
          MAVEN_GPG_PASSPHRASE: MAVEN_GPG_PASSPHRASE